---
- name: Install build dependencies for git
  become: yes
  become_method: sudo
  apt:
    name:
      - gcc
      - git-core
      - gettext
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libssl-dev
      - libz-dev
    state: present
    update_cache: yes
  tags: [ 'gitr', 'deps' ]

- name: Install run-time dependencies for git regression tests
  become: yes
  become_method: sudo
  apt:
    name:
      - cvs
      - cvsps
      - perl
      - sqlite3
    state: present
    update_cache: yes
  tags: [ 'gitr', 'deps' ]
