---
- name: Install build dependencies for git
  become: yes
  become_method: sudo
  zypper:
    name:
      - gcc
      - gettext
      - git-core
      - libcurl-devel
      - libexpat-devel
      - libopenssl-1_1-devel
    state: present

- name: Install run-time dependencies for git regression tests
  become: yes
  become_method: sudo
  zypper:
    name:
      - cvs
      - cvsps
      - perl-Test-Harness
      - subversion
      - subversion-perl
    state: present
