---
- name: Install build dependencies for pynfs
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  vars:
    packages:
      - gcc
      - git-core
      - make
      - krb5-devel
      - python3-devel
      - swig
      - python3-gssapi
      - python3-ply
